[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "@openzeppelin/=lib/openzeppelin-contracts/contracts/", "v3-periphery/=lib/v3-periphery/contracts/", "v2-periphery/=lib/v2-periphery/contracts/", "pancake-v3-core/=lib/pancake-v3-contracts/projects/v3-core/contracts/"]

[rpc_endpoints]
localhost = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
